### ISSUE TITLE
Does the plugin work with React?

### ISSUE THREAD

**Issue by wzup** [jbsouvestre/inline-style-loader#2]
Can I use it with React?

**Comment by jbsouvestre** [comment]
No, you'll get this error: 

> The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX. 

But I don't really see why you would want to use this with React, since it already does something like that  out of the box: https://facebook.github.io/react/docs/dom-elements.html#style
